project:
  type: book

book:
  title: "医学英語: フレイルで理解する臨床論文の読み方"
  author: "馬場 美彦"
  date: "11/4/2024"
  chapters:
    - index.qmd
    - design.qmd
    - frailty.qmd
    - part: meta.qmd
      chapters:
        - meta_intro.qmd
    - part: ct.qmd
      chapters:
        - rct_intro.qmd
    - part: observation.qmd
      chapters:
        - crosssectional_intro.qmd
    - part: critical.qmd
      chapters: 
        - letter.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: style.css
    grid:
      margin-width: 350px
  pdf:
    pdf-engine: xelatex
    documentclass: bxjsbook
    classoption: oneside,xelatex,ja=standard
    output-file: "How"
    output-ext:  "pdf"

reference-location: margin
citation-location: margin

